language: php

php:
  - 7.2

services:
  - mysql

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - CODACY_PROJECT_TOKEN=a3ba86a8a97846e9a8bca68975f22c66

install:
  - >
    composer install;
    composer build:package:link

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit -c Build/UnitTests.xml Tests/Unit/ --coverage-clover .build/coverage.xml;
    .build/bin/codacycoverage clover .build/coverage.xml
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    .build/bin/phpunit -c Build/FunctionalTests.xml Tests/Functional/
