services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.security:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['security']

  policy.access:
    class: TYPO3\AccessControl\Policy\AbstractPolicy
    factory: ['@TYPO3\CMS\Security\AccessControl\Policy\PolicyManager', 'getPolicy']
    arguments:
      - '@cache.security'

  TYPO3\CMS\Security\:
    resource: '../Classes/*'

  TYPO3\CMS\Security\AccessControl\Policy\PolicyManager:
    arguments:
      - '@cache.security'

  TYPO3\AccessControl\Policy\PolicyInformationPoint:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\EventDispatcher\EventDispatcher'

  TYPO3\AccessControl\Policy\PolicyDecisionPoint:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\EventDispatcher\EventDispatcher'
      - '@policy.access'
      - '@TYPO3\AccessControl\Policy\PolicyInformationPoint'
      - '@TYPO3\CMS\Security\AccessControl\Attribute\AttributeContext'