services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.security:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['security']

  TYPO3\CMS\Security\:
    resource: '../Classes/*'

  TYPO3\CMS\Security\Policy\PolicyDecisionPoint:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Context\Context'
      - '@TYPO3\CMS\Core\EventDispatcher\EventDispatcher'
      - '@cache.runtime'
      - '@TYPO3\CMS\Security\Policy\PolicyConfigurationLoader'
      - '@TYPO3\CMS\Security\Policy\PolicyFactory'
      - '@TYPO3\CMS\Security\Policy\PolicyInformationPoint'

  TYPO3\CMS\Security\Policy\PolicyConfigurationLoader:
    arguments:
      - '@cache.security'

  TYPO3\CMS\Security\Policy\PolicyInformationPoint:
    arguments:
      - '@TYPO3\CMS\Core\EventDispatcher\EventDispatcher'
      - '@cache.runtime'